name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    
  build:
    environment: wikibot-ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Variable Substitution appsettings file for tests
      uses: microsoft/variable-substitution@v1
      with:
        files: 'Wikibot.Tests/appsettings.json'
      env:
        AppSettings.WikiRequestPage: "${{ secrets.WikiRequestPage}}"
        AppSettings.RootAdminEmailAddress: "${{ secrets.RootAdminEmailAddress }}"
        AppSettings.BotRequestTemplate: "${{ secrets.BotRequestTemplate }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
