# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./wikibot-ui

    steps:
    - uses: actions/checkout@v3
      with:
        cache-dependency-path: ./wikibot-ui
    - name: Use Node.js ${{ matrix.node-version }}
    
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./wikibot-ui
    - run: npm install --save @fortawesome/fontawesome-free
    - run: npm install bindings@1.5.0 --legacy-peer-deps
    - run: npm install nan@2.16.0 --legacy-peer-deps
    - run: npm install file-uri-to-path@1.0.0 --legacy-peer-deps
    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present --legacy-peer-deps
    - run: npm test
