name: .NET

on:
  push:
    branches: [ releases/** ]
  pull_request:
    branches: [ releases/** ]

jobs:
  build:

    runs-on: windows-latest
    environment: wikibot-env
    env:
        Deploy_Service_URL: "${{ secrets.DeployUrl }}"
        Deploy_IIS_Path: "${{ secrets. DeployIISAppPath }}"
        PublishUsername: "${{ secrets.DeployUsername }}"
        EncryptedPassword: "${{ secrets.EncryptedDeployPassword }}"
        ApplicationDB_Connection: "${{ secrets.ApplicationDB }}"
        JobDB_Connection: "${{ secrets. JobDB }}"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Variable Substitution appsettings file for deployment
      uses: microsoft/variable-substitution@v1
      with:
        files: 'Wikibot.App/appsettings.json'
      env:
        WikiRequestPage: "${{ secrets.WikiRequestPage }}"
        RootAdminEmailAddress: "${{ secrets.RootAdminEmailAddress }}"
        BotRequestTemplate: "${{ secrets.BotRequestTemplate }}"
        WikiLogin.Username: "${{ secrets.WikiLoginUsername }}"
        WikiLogin.Password: "${{ secrets.WikiLoginPassword }}"
        WikiLogin.APIUrl: "${{ secrets.WikiLoginAPIUrl }}"
        WikiLogin.APIPath: "${{ secrets.WikiLoginAPIPath }}"
    - name: Deploy
      run: dotnet publish -p:PublishProfile=IISProfile -c:Release -p:AllowUntrustedCertificate=true

